# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Allergy Compass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Allergy Compass
  pod 'M13Checkbox'


  target 'Allergy CompassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Allergy CompassUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
